apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-api-user
  labels:
    app: udagram-api-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udagram-api-user
  template:
    metadata:
      labels:
        app: udagram-api-user
    spec:
      containers:
        - name: udagram-api-user
          image: datpham134/udagram-api-user:latest
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: database-user
                  key: database-username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-password
                  key: database-password
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: postgres-host
                  key: postgres-hosting
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-db-name
                  key: postgres-db-name-key
            - name: AWS_BUCKET
              valueFrom:
                secretKeyRef:
                  name: aws-bucket
                  key: aws-bucket-key
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: aws-region
                  key: aws-region-key
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: jwt-secret-key
